### ISSUE TITLE
Split Voronoi

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/autocnet#173]
Ability to compute Voronoi diagrams for adjacency graphs that are not complete. For example, if two images overlap one image but do not overlap each other, two different Voronoi's need to be computed.

**Comment by jlaura** [comment]
I think that this is probably on hold until #160 has resulted in a design decision.  Then we can take the (awesome) work by @acpaquette and integrate it into a system to all the application of methods (including Voronoi).

**Comment by jlaura** [comment]
Closed by #186.  :+1: @acpaquette and @Kelvinrr
