### ISSUE TITLE
The edge object has a method that is monkey patched in names `match`.  This method needs to reset the mask attribute to be empty before being called.  Decorators are an option.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/autocnet#191]

**Comment by evindunn** [comment]
@jlaura I want to do this while keeping  the` _add_matches()` functionality in mind, but I can't find where it's implemented. If it isn't implemented yet, should I add a keyword to Edge.match()? Something like `append_matches=bool`
