### ISSUE TITLE
The matcher.feature_matcher funcs should not have access to self.  Rewrite as funcs without class access.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/autocnet#192]

**Comment by jlaura** [comment]
Related to #191.  This is mainly a code smell issue.

**Comment by evindunn** [comment]
- cpu_matcher.match() / cuda_matcher.edge() take "edge" instead of self
- static matcher methods are patched in to static Edge._match(edge)
- member method Edge.match() calls Edge._match(self)
