### ISSUE TITLE
As a user, it is possible to compute the potential overlap between two nodes and store the overlap as an attribute on the edge.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/autocnet#195]
The idea here is that a node's geotransform object and geospatial metadata (corner coordinates, footprint, etc.) store enough information that an intersection minimum bounding rectangle or polygon can be computed.  From these, the overlapping area (in pixel space) of both nodes can be approximated.  This area can then be used as an a priori constraint on matching.

- [ ] The plio library has been extended to compute the intersection between two OGR bounding polygons extracted from Qub footprints.  This is intentionally constrained to the QUB format.
- [ ] Using two bounding polys the intersection can be stored at edge['source_mbr'] and edge['destin_mbr'] attributes.  This makes the assumption that the nodes overlap at a single, contiguous point.  That assumption may be wrong, but I would prefer to address multiple discontiguous overlaps in a later ticket as this should be an edge case.

**Comment by evindunn** [comment]
edge["source_mbr"] & edge["destin_mbr"] are populated by edge.compute_intersection() using plio 0.1.1
