### ISSUE TITLE
Spike: As a user, I can apply any function that operates on an edge to only the estimated (MBR) overlap between the nodes.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/autocnet#196]
This is a design question.  We have a multitude of methods that operate on a node or edge that could be constrained for just the overlapping area between images.  How best can the methods be extended to support the additional area constraint.  Off the top of my head, these include:

- [x] - keypoint extraction
- [ ] - coupled decomposition
- [x] - matching
- [x] - outlier detection
  - [x] - ratio
  - [x] - symmetry
  - [x] - homography
  - [x] - fundamental matrix
- [ ] - spatial suppression

Sub-pixel registration, punch through, and suppression work on a per correspondence basis and should not be impacted - I think.

**Comment by evindunn** [comment]
Matching was already done with Edge.match_overlap()

**Comment by evindunn** [comment]
Removed Edge.match_overlap(), instead have Edge.overlap_check() that creates a mask for the matches with both source_idx and destination_idx in the overlap

**Comment by evindunn** [comment]
@jlaura Can you take a look at my implementation of the Edge.overlap_constraint property? [https://github.com/evindunn/autocnet/commit/593b1bb7c81fafdf151d7714efd32b3c22958253](url)

**Comment by jlaura** [comment]
@evindunn Looks really good.  👍  

Tiny questions/ideas:

edge.py
- Line 234 - instead of duplicating the check for the bounding boxes, what if you check the property?  `if overlap and not self.overlap_constraint` warn and return none?
- Line 480 - do we need to automatically always use the overlap or should be let the user include it in the list of clean keys?  In other words, is expecting the user to use `clean_keys=['a', 'b', 'overlap', ...]` reasonable?


Tests look great and the modifications to decompose_and_match look good.  Very nice use of Python 'Falselyness' keeping this super concise and readable. (`overlap = kwargs.get("overlap", False)`.

**Comment by evindunn** [comment]
Pull Request #212
