### ISSUE TITLE
Current installation instructions fail

### ISSUE THREAD

**Issue by michaelaye** [USGS-Astrogeology/autocnet#241]
```bash
(autocnet) └─❱❱❱ conda install -c jlaura autocnet-dev                         +7771 22:50 ❰─┘
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - autocnet-dev
  - plio

Current channels:

  - https://conda.anaconda.org/jlaura/osx-64
  - https://conda.anaconda.org/jlaura/noarch
  - https://conda.anaconda.org/menpo/osx-64
  - https://conda.anaconda.org/menpo/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/conda-canary/osx-64
  - https://conda.anaconda.org/conda-canary/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/NSIDC/osx-64
  - https://conda.anaconda.org/NSIDC/noarch
```

This is run on macOS 10.12.6, after I added the channels and created a new environment called "autocnet" (as can be seen by above shell prompt).

**Comment by michaelaye** [comment]
First, I thought, this comes from the conda package only being created for Python 3.5, but after creating a 3.5 conda env, it now fails at the plio package, which does not seem to be available both on conda and pip. :(

**Comment by jlaura** [comment]
It looks like you got this fixed aimed at the USGS anaconda org?  I need to make sure that plio is also building for 3.6.

**Comment by michaelaye** [comment]
Well USGS channel was the only channel that had plio available, but yes, to have everything working on py3.6 would be preferable.

--
K.-Michael Aye
Martian Polar Science (Co-I NASA Solar Systems Workings)
Cassini ISS and UVIS Rings analyses
Planetary Python specialist
