### ISSUE TITLE
MKL library actively used?

### ISSUE THREAD

**Issue by michaelaye** [USGS-Astrogeology/autocnet#250]
Because of a current confusion within the conda system, currently the install is mixing default-channel intel MKL packages with the rest of the conda-forge packages.
If your code doesn't mind to use the openblas libraries instead, i think it's less error-prone to force conda to use the openblas packages from conda-forge for increased consistency?
If you agree, I can update the install commands to include this.

**Comment by jlaura** [comment]
OpenBLAS should work just fine. PR appreciated!

**Comment by jlaura** [comment]
This has been open for ~1 year without any changes. Closing for now as we do not see pushing a PR to address this in the near term.
