### ISSUE TITLE
ciratefi default incorrect

### ISSUE THREAD

**Issue by abhijithrajan** [USGS-Astrogeology/autocnet#273]
Hi @jlaura, noticed a small error. The Ciratefi function call default for use_percentile is False, while the default threshold values and the help assume it will be True.

`def ciratefi(template, search_image, upsampling=1, cifi_thresh=95, rafi_thresh=95, tefi_thresh=100,
             use_percentile=False, alpha=math.pi/16, scales=[0.5, 0.57, 0.66,  0.76, 0.87, 1.0],
             radii=list(range(1, 12)), verbose=False)`

**Comment by Kelvinrr** [comment]
Yeah, that's a weird mistake, the default value is correct in all other methods. I originally wrote it, just a simple oversight.

**Comment by Kelvinrr** [comment]
closed by #274
