### ISSUE TITLE
Write function to run overlap SQL queries

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/autocnet#309]
It's really annoying having to run these by hand, we should just have functions that can run them.

**Comment by jlaura** [comment]
How about we put raw query into a file (along side the triggers.py) with a `.py` ending. Then, we can import them and have a generic, 'run SQL' dispatcher. Probably best to put it onto the candidate graph?

**Comment by jessemapel** [comment]
Don't we want these queries to run as part of the candidate graph construction?

**Comment by jlaura** [comment]
Ideally, we would want the query to run any time a new image is pushed into the graph (so a trigger). This is to ambitious right now, so in creation, but after the images have been loaded. So running at the end of the constructor would be fine.
