### ISSUE TITLE
Inconsistent Matches Table Access

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/autocnet#311]
The matches table is being accessed inconsistently due to graph edges being directional instead of bi-directional.

Somewhere along the line when submitting jobs to the cluster "edges" are being defined as (destination, source) instead of (source, destination). This affects queries on the matches table where the "edge" being queried is source: 10, destination: 3 which has no matches since all matches for that edge are stored as source: 3, destination: 10.

**Comment by jlaura** [comment]
This seems like a 2 part issue. The first is the code base. The second is the database. I wonder if it makes sense to write a database trigger / integrity checker that raises an error if  destination >= source.  The = is just an added precaution.

Thoughts?

**Comment by jessemapel** [comment]
Can we abstract destination >= source out in the model?

**Comment by jlaura** [comment]
That is a really good question. I think that we could use a validator to do this.  

https://docs.sqlalchemy.org/en/13/orm/mapped_attributes.html#simple-validators

This would need to make sure to update the source/source_idx and destination/destination_idx fields.
