### ISSUE TITLE
Make image_path optional in NetworkNode constructor

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/autocnet#314]
We should be able to get the image_path by querying the Images table.

**Comment by jessemapel** [comment]
For example I am doing things like

```
res = session.query(Images).filter(Images.id == source_id).first()
source = NetworkNode(node_id=source_id, image_path=res.path)
```

**Comment by jlaura** [comment]
I think that this is related to #313. To solve this, we can write a `get` classmethod on the network node along the lines of:

```python
    @classmethod
    def get(cls, key, by='id'):
        session = Session()
        # For now, just use the PATH to determine if the node/image is in the DB
        field = getattr(Images, by)
        res = session.query(Images).filter(field == key).one()
        session.close()
        if res:
            return cls(node_id=res.id, image_path=res.path)
```
This can then be used in the constructor. Depending on the solution to #313 - this might not belong on the object, rather, this might below on the object that represents a table.

**Comment by jessemapel** [comment]
I don't think this is worth doing for the moment.
