### ISSUE TITLE
Appending measures to DB points and measures tables 

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/autocnet#327]
How should this be handled?

**Comment by ladoramkershner** [comment]
I have a portion of code (PR #460) in autocnet.matcher.cross_instrument_matcher.propagate_control_network that adds measures to a point in the database if the point's geometry already exists (starting here: https://github.com/ladoramkershner/autocnet/blob/6b7df8200b7ab6d49d942068cf854c028f9fb55f/autocnet/matcher/cross_instrument_matcher.py#L445). Is this acceptable?

**Comment by jlaura** [comment]
@ladoramkershner Yes. I think that is a good way to handle this. I am going to close and we can reopen as needed.
