### ISSUE TITLE
Target Name is not included in control network outputs

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#348]
If a target name is not included, to_isis() outputs a control network with TargetName = None. Instead it should probably error and not write out. 

Additionally, speaking with @Kelvinrr and @jessemapel and we are thinking maybe a target name should be included in the config file under spatial. We don't want to over complicate the config file, but since we are inputting radii and a proj string in there anyways, a target name doesn't seem too difficult.

**Comment by jlaura** [comment]
Having a target name in the spatial section makes a lot of sense I think. I would rather include verbosity   in one place than scatter it all over the API. This is probably a good place to centralize.
