### ISSUE TITLE
CSM projection and isis campt

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#353]
There is an offset between the isis cube footprints and the cnet output by the autocnet demo notebook. When visualizing in qmos (see below) the cnet points seem to be downtrack from where you might expect them to be.

![image](https://user-images.githubusercontent.com/42873279/60304857-7f307a80-98ef-11e9-8b9d-d52d883e1c68.png)

When further investigating, grabbing the latitude and longitude of a point from the bundle adjust output [prefix]_bundleout_points.csv and projecting it to image space using campt and csm groundToImage results in values that are 6.5 and 0.5 pixels off in the line and sample direction. Additionally,
'''locus = ncg.nodes[8]['data'].camera.imageToRemoteImagingLocus(csmapi.ImageCoord(isis_line-0.5, isis_samp-0.5))
print(locus.direction.x, locus.direction.y, locus.direction.z)'''

produced slightly different values than what is seen for the point direction from campt, but on the order of e-6 and e-7. 

This process was completed twice with control points from near the top and near the bottom of a single image. I can repeat for other images, or I can create a function to cycle through all the points to see if this is a constant trend. Just want to get other people's thought beforehand.

**Comment by jessemapel** [comment]
Some other debugging options are:

1. Turning on debug logging by setting `m_logFile` to where we want the log output in the USGSCSM  state.
1. Running the imageToGround direction with Knoten's dem intersection and campt all around the image.

**Comment by jessemapel** [comment]
This may be due to a difference in which kernels ISIS and pfeffernusse are using.

In the PDS release (which pfeffernusse uses), there are updated SPKs available. ISIS does not use these kernels. I am going to look into updating the ISIS data area to use the updated SPKs.

**Comment by jessemapel** [comment]
Even more digging, it turns out we're not writing out the ground point for any of our control points. So, ISIS is recomputing the ground point based on the image measures too. This is why we're seeing differences between qgis and qmos
