### ISSUE TITLE
Making cluster jobs more efficient with accurate resource allocation estimates

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#380]
It was suggested that we look into resource allocation to speed up our cluster jobs. I looked at the previously submitted jobs and it looks like the only thing we could really improve on is asking for less memory (we are currently asking for 8G for each job, which seems like overkill) and directly specifying all of our resources (**cpus**, memory, **nodes**, partition, and walltime).  Right now we just are not specifying cpus and node counts for each job. This should be an easy change, I was just looking for input!

**Comment by ladoramkershner** [comment]
Additionally, we could look at the amount of memory needed on average for each cluster job that we dispatch (place points, subpixel register, and fundamental) and specify memory approximations for each job??

**Comment by jlaura** [comment]
All of these items can be parametrized in the plurmy call. Feel free to make tweaks and test to see what works.

**Comment by ladoramkershner** [comment]
I talked with Craig again and the defaults for cpus and nodes are 1, so we are fine there. However, we should switch the requested memory down to 1 Gb. The jobs now are mostly using on the order of 0.1 Gb, so 1 is a very safe over prediction and it also allows us to fully utilize nodes.

Before with 8 Gb per cpu we could only use 16 out of the 28 cpus available on any given node due to memory limitations. It goes much faster too!

**Comment by jlaura** [comment]
:+1: Sounds like a PR is in order.

**Comment by ladoramkershner** [comment]
#381 is just a change in the sample.yml I am not sure if other will see this, since they probably already have personal config files that are not tracked by git

**Comment by jlaura** [comment]
@ladoramkershner Is this closable?

**Comment by ladoramkershner** [comment]
I am not sure. I ended up upping the resource back to 8Gb because I was running into memory issues and I haven't heard any complaints (yet). So we could close it with the caveat of opening a similar issue if needed.
