### ISSUE TITLE
Broken to_isis and from_isis methods

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/autocnet#387]
Both of these methods are potentially failing due to mismatching column names/renames within the methods themselves. 

This is the result of a change in PLIO to allow:
```
cnet_df = plio.from_isis('Path/to/some/controlnetwork.cnet')
plio.from_isis(cnet_df, 'Path/to/some/new_controlnetwork.cnet')
```

**Comment by jlaura** [comment]
I believe this has been fixed.
