### ISSUE TITLE
cluster_subpixel_register_points attempts to register few points multiple times

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#397]
When running large cluster jobs, certain points will be subregistered multiple time (have seen up to three attempts on one point) and on the nth attempts, the following message will be output. 

```
Subpixel registering point 40
Traceback (most recent call last):
  File "/home/ladoramkershner/miniconda3/envs/autocnet_local/bin/acn_subpixel", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/work/users/ladoramkershner/projects/autocnet/bin/acn_subpixel", line 55, in <module>
    main(msg, config)
  File "/work/users/ladoramkershner/projects/autocnet/bin/acn_subpixel", line 39, in main
    iterative_phase_kwargs=msg['iterative_phase_kwargs'],
KeyError: 'iterative_phase_kwargs'
```

From what I can tell this is not detrimental at all to the effectiveness of the code overall, it is just a little annoying. Thought I would throw it up here for a future fix one a day when we have completed ALL of the tickets :smiling_imp:

**Comment by jlaura** [comment]
@ladoramkershner Is this still an issue?

**Comment by ladoramkershner** [comment]
I have not seen this issue lately and I am seeing the exact number of logs as I am seeing points in the database, plus an empty queue. So that would suggest no points are being registered twice. Additionally, we no longer use 'acn_subpixel' since PR #438.

I would be comfortable closing this issue.
