### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by oleg-alexandrov** [USGS-Astrogeology/autocnet#401]
In the readme file, the link to documentation:

https://usgs-astrogeology.github.io/autocnet/

is broken. It would also be nice to add to the readme itself some documentation. I looked around the repository, including the notebooks, and I could not get a quick idea of what this software is doing.

**Comment by jlaura** [comment]
Docs are auto deploying correctly now. https://usgs-astrogeology.github.io/autocnet/
