### ISSUE TITLE
Speed up generate_ground_points() and propagate_control_network()

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#405]
Currently everything done in these two functions are done in serial. Due to the resolution disparity between globally controlled data sets and the need-to-be-controlled data, not many points can survive the matching that is used to propagate the generated ground points into the product data. 

The current solution is to throw a lot of ground points down and hope enough survive. This makes this grounding process SLOW. I think these functions could be sped up with consolidated code and/or parallelization.

**Comment by jlaura** [comment]
Closing because I think @Kelvinrr fixed this with his parallel implementation. We should reopen if not.
