### ISSUE TITLE
point geom using -180 to 180 domain

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/autocnet#415]
while the overlay are using 0 to 360. This is an issue for visualization where points/overlaps are not aligning because of the different domains.

**Comment by ladoramkershner** [comment]
Pull request #416 address this problem by hard coding the pyproj to work in the 360 lon domain (and consolidating all pyproj calls to one central location). I do not think this should be the permanent solution. When that PR is merged, this ticket can be closed. However, issue #402 is still open and discusses further solutions.

**Comment by ladoramkershner** [comment]
Closing now since PR #416 was merged. See issue #402 to see more robust handle of point geom domain.
