### ISSUE TITLE
config_parser.py is in root directory, not in code

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#424]
This means the file does not get copied over properly to the site-packages area when doing a setup.py install or develop causing compiling errors if working on jupyter hub.

Simple fix. Move config_parser.py to the root of the code (autocnet/autocnet). After that is moved, the import of config_parser in init.py (line 29) is changed to `from autocnet.config_parser import parse_config`

**Comment by jlaura** [comment]
closed with #425
