### ISSUE TITLE
Interesting feature search can move poitn off image

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#426]
In spatial/overlap.py -> place_points_in_overlap()

The following piece of code
```
image, _, _ = clip_roi(node.geodata, sample, line, size_x=size, size_y=size)
interesting = extract_most_interesting(image)
newsample = sample + (interesting.x - size)
newline = line + (interesting.y - size)
```

can result in negative newline or newsample. I am not sure if this is because the orb detector is finding its most interesting feature off of the image, or if the conversion from interesting to newline/newsample is flawed. However, this process is all operating on a single image, so it seems like this shouldn't even be possible if the code were doing what we think it is doing.

**Comment by jessemapel** [comment]
This could be caused by clip_roi downsizing the region if it bumps against the edge of the image.

**Comment by jlaura** [comment]
The problem is that `clip_roi` can return an image that is not of shape `size*2, size*2`. Here is a test that shows the fix:

```python
from collections import namedtuple
import pytest

Interesting = namedtuple('Interesting', ['x', 'y'])


@pytest.mark.parametrize("size, sample, line, image_samples, image_lines, interesting_x, interesting_y, expected_x, expected_y",
                         [(20, 30, 30, 40, 40, 20, 20, 30, 30), # clip_roi return is the expected size
                          (20, 10, 30, 10, 40, 5, 20, 10, 30),
                          (20, 10, 30, 10, 40, 4, 20, 9, 30),
                          (20, 10, 30, 10, 40, 8, 20, 13, 30)
                          ])
def test_clip_roi_and_extract_most_interesting(size,
                                               sample, line,
                                               image_samples, image_lines,
                                               interesting_x, interesting_y, 
                                               expected_x, expected_y):
    image_shape = (image_lines, image_samples)
    interesting = Interesting(interesting_x, interesting_y)
    newsample = sample + (interesting.x - image_shape[1]/2)
    newline = line + (interesting.y - image_shape[0]/2)

    assert expected_x == newsample
    assert expected_y == newline
```

I'll get a PR open with the fix. I am torn on the test - because the above does not exercise the API at all and to exercise the above would be a mock party as the error is not well encapsulated.
