### ISSUE TITLE
to_isis does not write out weights

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#440]
This is related to a plio issue (https://github.com/USGS-Astrogeology/plio/issues/144), where there is no 'GoodnessOfFit' keyword in the protobuf translation file (ControlPointFileEntryV0005_pb2.py).

Once that is resolved. I am thinking weight could be written out to the network so it is much easier to evaluate while being fully in qnet (not having to cross reference the database).

**Comment by jlaura** [comment]
Is this that the subpixel coordinates are not being written or that the weights are not being written? or both?

**Comment by ladoramkershner** [comment]
Subpixel coordinates are getting written out, the weights are NOT being written out.

**Comment by jlaura** [comment]
This should have been fixed in #454
