### ISSUE TITLE
Look further into subpixel matcher implimentation

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#453]
Currently, a network that is subpixel registered in autocnet will not result in a jigsaw bundle that converges. It does not fail or diverge, but it does require a round of pointreg for the bundle to converge. 

I compared the amount of shift in autocnet subpixel register and the corresponding (additional) shift during pointreg. Regardless of the autocnet shift amount, pointreg adjusted the points by a few pixels. For template+phase matching it was ~0-3 pixels of shift and for template only matching it was ~0-2 pixel shift.

So, it seems:
a.) There is still a difference between pointreg and autocnet's template subpixel registration.
b.) The phase matcher is currently not providing the extra precision we were hoping for and may be doing some harm. 

We should look more in depth into the differences between the template matching method in autocnet and ISIS's pointreg. The difference may just be a different estimation technique for the affine transformation, or something larger. Additionally, more research should be done into the phase matcher. However, this is a secondary goal since it can just be switched off and, assuming the template matcher is accurate, will result in a converging bundle.

**Comment by jlaura** [comment]
@ladoramkershner Is this closable with all the work that has been done the last few weeks?

**Comment by ladoramkershner** [comment]
Not just yet, the issue was found but the necessary code has not been PRed into the repo yet. 

I believe this issue was being caused by points not getting ignored if they failed geom_match with an exception. It fails loudly, but doesn't set the measure to ignore. So we have 'subpixel registered' measures that are actually at their apriori location.
