### ISSUE TITLE
Full Null Fit Chips make it through geom_match

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#481]
I think this problem is three fold:

1.) (place_points_in_overlap) We are not checking to see if we are laying down our initial point measure in null regions, however extract_most_interesting with extractor_method='orb' (default) will error if it is handed an array containing null data values. Specifically, detector.detectAndCompute on line 72 will hand back NoneType descriptors. BUT extract_most_interesting will not error when you use 'vlfeat' extractor_method option, so this still needs to be addressed. 

2.) (place_points_in_overlap) We are not checking to see if the reference measure we place (that goes through extract_most_interesting) is being propagated to null areas in their overlapping images. 

3.) (geom_match/subpixel_template) We are not evaluating the template matching chips to see if it contains all null data.

There seems to be a related issue in plio, where null ISIS cube data is not being read in by GeoDataset as expected (for example, read in null data is -3.40282266e+38, but should be -3.4028227e+38) which makes it hard to evaluate for null data specifically.

Side Note: When someone looks into this, I am curious what kind of behavior we get out of autocnet for partial valid data, should we add checks to make sure a certain portions of the chip data is valid?

**Comment by ladoramkershner** [comment]
Oh hey jk, the read in vs defined isis null pixel values are the same with a difference of rounding errors. My eyes glazed over a bit when trying to compare them.

**Comment by ladoramkershner** [comment]
Associated gist with some work I did looking at this issue. It is not much, but it has an example which is nice so other don't have to dig! (cubes are associated with the oxia palus quad)

https://gist.github.com/ladoramkershner/7591b2a60bcf9a63afa3f89529e5e79d

**Comment by jlaura** [comment]
I believe that this issue has been solved with a NULL check when pulling an ROI. I am going to close. Please reopen if this is still an issue!
