### ISSUE TITLE
error installing setup.py

### ISSUE THREAD

**Issue by gcush** [USGS-Astrogeology/autocnet#499]
Trying to install autocnet from the instructions below, I get an error at the command '>python setup.py install'

These are the instructions I followed:

1. Clone repo with: `git clone https://github.com/Kelvinrr/autocnet.git ` 

2. cd into repo: `cd autocnet` 

3. Checkout dev: git checkout dev 

4. Install dependencies: `conda env create –f environment.yml -n autocnet` 

5. Activate new environment: `conda activate autocnet` 

6. Install autocnet: `python setup.py install` 

Here's the error I get at this point:

gcushing@barchan~/anaconda3/autocnet$ unsetisis
ISIS unset
gcushing@barchan~/anaconda3/autocnet$ conda activate autocnet
(autocnet) gcushing@barchan~/anaconda3/autocnet$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import autocnet
  File "/home/gcushing/anaconda3/autocnet/autocnet/__init__.py", line 25, in <module>
    from autocnet.graph.network import CandidateGraph, NetworkCandidateGraph
  File "/home/gcushing/anaconda3/autocnet/autocnet/graph/__init__.py", line 1, in <module>
    from . import edge
  File "/home/gcushing/anaconda3/autocnet/autocnet/graph/edge.py", line 13, in <module>
    from autocnet.graph.node import Node
  File "/home/gcushing/anaconda3/autocnet/autocnet/graph/node.py", line 14, in <module>
    from knoten.csm import generate_latlon_footprint, generate_vrt, create_camera, generate_boundary
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/knoten/__init__.py", line 17, in <module>
    libusgscsm = ctypes.CDLL(libusgscsm_path)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/gcushing/anaconda3/envs/autocnet/lib/libusgscsm.so.1: undefined symbol: _ZN3ale18getDistortionModelEN8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS0_14adl_serializerEEE
(autocnet) gcushing@barchan~/anaconda3/autocnet$
(autocnet) gcushing@barchan~/anaconda3/autocnet$

Cheers!

**Comment by jlaura** [comment]
@gcush Can you please post the output of `conda list` when in your autocrat environment. It looks like you are having environment issues.

**Comment by jessemapel** [comment]
This is a result of the setup.py using a bad dev build of usgscsm. Run `conda install -c conda-forge usgscsm` to pull a proper release build.

**Comment by jessemapel** [comment]
I am working on getting a usgscsm release with the latest code out so that autocnet can get off of a dev build.

**Comment by gcush** [comment]
Hi Jesse,

Thank for working on this!

This issue when I try to install:


Preparing transaction: done
Verifying transaction: failed

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /usgs/cpkgs/anaconda3_linux
  uid: 2132
  gid: 1800


Cheers~
Glen



Glen Cushing
U.S. Geological Survey
Astrogeology Science Center
2255 N. Gemini Dr.
Flagstaff, AZ 86001

________________________________

**Comment by jessemapel** [comment]
@gcush It seems like you don't actually have an anaconda environment active. Can you check that you have your autocnet environment activated before you run that command.

**Comment by gcush** [comment]
I was about to ask where to find my autocrat environment but figured it out just in time....



Glen Cushing
U.S. Geological Survey
Astrogeology Science Center
2255 N. Gemini Dr.
Flagstaff, AZ 86001

________________________________
