### ISSUE TITLE
autocnet error running acn_cd

### ISSUE THREAD

**Issue by gcush** [USGS-Astrogeology/autocnet#507]
I 'seem' to have autocnet installed correctly, but I'm getting this error now - I'm trying to reproduce the example in Colin's change-detection cookbook. The ISIS3 preprocessing seems to have gone smoothly - or, at least it produced a pair of properly projected images - although Kelvin suggested it may be a PVL error that came from the processing. -thanks!

(autocnet) bash-4.2$
(autocnet) bash-4.2$
(autocnet) bash-4.2$ acn_cd /work/users/gcushing/acn/ESP_012024_1440_RED8.27250.29250.cub /work/users/gcushing/acn/ESP_020661_1440_RED4.34000.36000.cub /work/users/gcushing/acn/test.tif --map /usgs/cpkgs/anaconda3_linux/envs/isis4.2.0-RC1/appdata/templates/maps/equirectangular.map -c /work/users/gcushing/acn/cd_config.yml -r -w -a okb

Traceback (most recent call last):
  File "/home/gcushing/anaconda3/envs/autocnet/bin/acn_cd", line 4, in <module>
    __import__('pkg_resources').run_script('autocnet==0.2.6', 'acn_cd')
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/autocnet-0.2.6-py3.7.egg/EGG-INFO/scripts/acn_cd", line 112, in <module>
    cg.to_isis(cnet_path)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/autocnet-0.2.6-py3.7.egg/autocnet/graph/network.py", line 1295, in to_isis
    apriori_geom = np.array(point_info(self.nodes[zero_group.image_index]['data'].geodata.file_name, zero_group.x, zero_group.y, 'image')['BodyFixedCoordinate'].value) * 1000
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/autocnet-0.2.6-py3.7.egg/autocnet/spatial/isis.py", line 84, in point_info
    pvlres = pvl.loads(pvlres)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/pvl/__init__.py", line 113, in loads
    return decoder.decode(data)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/pvl/decoder.py", line 230, in decode
    module = PVLModule(self.parse_block(stream, self.has_end))
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/pvl/decoder.py", line 249, in parse_block
    statement = self.parse_statement(stream)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/pvl/decoder.py", line 304, in parse_statement
    return self.parse_assignment(stream)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/pvl/decoder.py", line 475, in parse_assignment
    self.ensure_assignment(stream)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/pvl/decoder.py", line 466, in ensure_assignment
    self.expect(stream, self.assignment_symbole)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/pvl/decoder.py", line 163, in expect
    self.raise_error(msg % (actual, expected), stream)
  File "/home/gcushing/anaconda3/envs/autocnet/lib/python3.7/site-packages/pvl/decoder.py", line 151, in raise_error
    raise ParseError(msg, stream.pos, stream.lineno, stream.colno)
pvl.decoder.ParseError: Unexpected token b'W' (expected b'='): line 1 column 9 (char 8)
(autocnet) bash-4.2$
(autocnet) bash-4.2$

**Comment by jessemapel** [comment]
@gcush Can you post your environment, the output of `conda list` while you have the autocnet environment active.

**Comment by gcush** [comment]
@jessemapel Hey Jesse, thanks for taking a look~

(autocnet) bash-4.2$ conda list
# packages in environment at /home/gcushing/anaconda3/envs/autocnet:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
affine                    2.3.0                      py_0    conda-forge
ale                       0.8.4            py37h99015e2_1    conda-forge
anyjson                   0.3.3           py37hc8dfbb8_1003    conda-forge
argon2-cffi               20.1.0           py37h8f50634_2    conda-forge
arrow                     0.17.0           py37hc8dfbb8_1    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
autocnet                  0.2.6                    pypi_0    pypi
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bcrypt                    3.2.0            py37h8f50634_1    conda-forge
blas                      2.17                   openblas    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2020.6.20        py37he5f6b98_2    conda-forge
cffi                      1.14.3           py37h00ebd2e_1    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
chardet                   3.0.4           py37he5f6b98_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colour                    0.1.5                      py_0    conda-forge
conda                     4.9.0            py37he5f6b98_1    conda-forge
conda-package-handling    1.7.2            py37hb5d75c8_0    conda-forge
coverage                  5.3              py37h8f50634_1    conda-forge
coveralls                 2.1.2                      py_0    conda-forge
cryptography              3.1.1            py37hff6837a_1    conda-forge
csm                       3.0.3.3              hc9558a2_0    conda-forge
csmapi                    1.0.1            py37h99015e2_0    conda-forge
cspice                    66                h516909a_1010    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py37h8f50634_1    conda-forge
cyvlfeat                  0.6.0            py37he9a287d_2    conda-forge
dask-core                 2.30.0                     py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
dill                      0.3.2              pyh9f0ad1d_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
entrypoints               0.3             py37hc8dfbb8_1002    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
ffmpeg                    4.1.3                h167e202_0    conda-forge
fiona                     1.8.13           py37h900e953_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.3               he06d7ca_0    conda-forge
freexl                    1.0.5             h516909a_1002    conda-forge
furl                      2.1.0                      py_0    conda-forge
gdal                      3.0.2            py37hbb6b9fb_6    conda-forge
geoalchemy2               0.6.3                      py_0    conda-forge
geopandas                 0.8.1                      py_0    conda-forge
geos                      3.8.0                he1b5a44_1    conda-forge
geotiff                   1.5.1                hbd99317_7    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.63.1               h5a9c865_0
gmp                       6.2.0                he1b5a44_3    conda-forge
gnutls                    3.6.13               h79a8f9a_0    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
h5py                      2.10.0          nompi_py37h513d04c_102    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h54c07f9_1110    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs-lite          2019.12.3        py37h161383b_3    conda-forge
imageio                   2.9.0                      py_0    conda-forge
importlib-metadata        2.0.0                      py_1    conda-forge
importlib_metadata        2.0.0                         1    conda-forge
infinity                  1.4                        py_0    conda-forge
iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
intervals                 0.8.1                      py_0    conda-forge
ipykernel                 5.3.4            py37hc6149b9_1    conda-forge
ipython                   7.18.1           py37hc6149b9_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.17.2           py37hc8dfbb8_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json-c                    0.13.1            hbfbb72e_1002    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_2    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kealib                    1.4.13               hec59c27_0    conda-forge
kiwisolver                1.2.0            py37h99015e2_1    conda-forge
knoten                    0.2.1                  py37_110    usgs-astrogeology
krb5                      1.17.1               hfafb76e_3    conda-forge
lame                      3.100             h14c3975_1001    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libarchive                3.3.3             hc47fbbf_1007    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdap4                   3.20.6               h1d1bd15_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgdal                   3.0.2                hefdf094_6    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
liblapacke                3.8.0               17_openblas    conda-forge
libnetcdf                 4.7.3           nompi_h9f9fd6a_101    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.10               h5a2b251_0
libpng                    1.6.37               hed695b0_2    conda-forge
libpq                     12.3                 h5513abc_2    conda-forge
libprotobuf               3.13.0.1             h8b12597_0    conda-forge
libsodium                 1.0.18               h516909a_1    conda-forge
libsolv                   0.7.16               h8b12597_0    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libspatialite             4.3.0a               h793db0d_0
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h576950b_1    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               11.0.0               hfc4b9b4_1    conda-forge
lz4                       3.0.2            py37hb076c26_1    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.6.1            py37he97bff5_0    conda-forge
markupsafe                1.1.1            py37hb5d75c8_2    conda-forge
matplotlib-base           3.3.2            py37hc9afd2a_1    conda-forge
mistune                   0.8.4           py37h8f50634_1002    conda-forge
more-itertools            8.5.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbclient                  0.5.0                      py_0    conda-forge
nbconvert                 6.0.7            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  he1b5a44_2    conda-forge
nest-asyncio              1.4.1                      py_0    conda-forge
nettle                    3.4.1             h1bed415_1002    conda-forge
networkx                  2.5                        py_0    conda-forge
nlohmann_json             3.9.1                he1b5a44_0    conda-forge
notebook                  6.1.4            py37hc8dfbb8_1    conda-forge
numpy                     1.19.2           py37h7ea13bd_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
opencv                    3.4.7            py37h8949d38_2    conda-forge
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
orderedmultidict          1.0.1                      py_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.3            py37h9fdb41a_2    conda-forge
pandoc                    2.11.0.1             hd18ef5c_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
passlib                   1.7.4              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
phonenumbers              8.10.14                    py_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.0            py37h718be6c_0    conda-forge
pip                       20.2.3                     py_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
plio                      1.2.4            py37hc8dfbb8_0    conda-forge
pluggy                    0.13.1           py37hc8dfbb8_3    conda-forge
plurmy                    0.1.1                    py37_0    usgs-astrogeology
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.3                 h8573dbc_2    conda-forge
proj                      6.2.1                hc80f0dc_0    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.8                      py_0    conda-forge
prompt_toolkit            3.0.8                         0    conda-forge
protobuf                  3.13.0.1         py37h3340039_1    conda-forge
psycopg2                  2.8.6            py37hb09aad4_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pvl                       0.3.0                      py_1    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py37hb5d75c8_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.4.2.post1      py37h12732c1_0    conda-forge
pyqt                      5.9.2            py37hcca6a23_4    conda-forge
pyrsistent                0.17.3           py37h8f50634_1    conda-forge
pysis                     0.6.4            py37hc6149b9_1    conda-forge
pysocks                   1.7.1            py37he5f6b98_2    conda-forge
pytest                    6.1.1            py37hc8dfbb8_1    conda-forge
pytest-cov                2.10.1             pyh9f0ad1d_0    conda-forge
python                    3.7.8           h6f2ec95_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywavelets                1.1.1            py37h161383b_3    conda-forge
pyyaml                    5.3.1            py37hb5d75c8_1    conda-forge
pyzmq                     19.0.2           py37hac76be4_2    conda-forge
qt                        5.9.7                h0c104cb_3    conda-forge
qtconsole                 4.7.7              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
redis-py                  3.5.3              pyh9f0ad1d_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py37h8526d28_1    conda-forge
ruamel_yaml               0.15.80         py37hb5d75c8_1003    conda-forge
scikit-image              0.17.2           py37h9fdb41a_3    conda-forge
scikit-learn              0.23.2           py37h6785257_0    conda-forge
scipy                     1.2.1            py37h09a28d5_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py37he5f6b98_2    conda-forge
shapely                   1.7.0            py37hb106bac_1    conda-forge
sip                       4.19.8          py37hf484d3e_1000    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
spiceypy                  3.1.1                      py_0    conda-forge
sqlalchemy                1.3.20           py37h8f50634_0    conda-forge
sqlalchemy-utils          0.36.6             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
terminado                 0.9.1            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2020.6.3                   py_0    conda-forge
tiledb                    1.7.0                hcde45ca_2    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.0.4            py37h8f50634_2    conda-forge
tqdm                      4.51.0             pyh9f0ad1d_0    conda-forge
traitlets                 5.0.4                      py_1    conda-forge
tzcode                    2020a                h516909a_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
usgscsm                   1.4.1                hc9558a2_0    conda-forge
util-linux                2.35             py37h7b058c1_2    conda-forge
vlfeat                    0.9.20            h14c3975_1002    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.5.1            py37hc8dfbb8_1    conda-forge
x264                      1!152.20180806       h14c3975_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.3                he1b5a44_2    conda-forge
zipp                      3.3.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.4                h3b9ef0a_2    conda-forge
(autocnet) bash-4.2$

**Comment by jessemapel** [comment]
@gcush Where did you run the change detection script? The error is from the PVL module having trouble parsing the output from campt. I'd expect there to be a print.prt file in the directory where you ran the provided command that contains the output of the campt call that we can look for where PVL says it errored.

**Comment by Kelvinrr** [comment]
@gcush I tried running it locally using the commands you posted and was not able to replicate. This is using code from the `dev` branch and a fresh environment from dev. Have you tried looking at the `print.prt` files as Jesse suggested? My suspicion is that there is an environmental problem causing Isis to fail, like required env vars not being defined or spice kernels missing, the `print.prt` file would give us a hint as to what is happening.

**Comment by Kelvinrr** [comment]
also worth mentioning, if you do not see a `print.prt` file where you ran the command, it's possible ISIS is not installed correctly. Check your ISISROOT env var and see if you can run `campt`/`mappt` from that install on one of the input cubes.

**Comment by jlaura** [comment]
I am going to close based on age. Please reopen as needed!
