### ISSUE TITLE
place_points_in_overlap doesn't lay down any points if interesting features are not found

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#524]
After finding an interesting feature, place_points_in_overlap runs a check that the updated (interesting) lon/lat is still in the overlap geometry. If the updated lon/lat is no longer in the overlap geometry, it reverts back to the original distribute_point_in_geom generated lon/lat. This seems to set the precidence that some points in an overlap are better than none.

However, if ppio is unable to find an interesting feature it just skips laying down points entirely.
https://github.com/USGS-Astrogeology/autocnet/blob/c7e9fec132060d58e491555d73956fe4bc4427bb/autocnet/spatial/overlap.py#L166

I think we should keep the original lon/lat points even if we cannot find an interesting feature.

**Comment by jlaura** [comment]
Fixed locally and in #527
