### ISSUE TITLE
Test Suite Run instructions provide an error on DB setup?

### ISSUE THREAD

**Issue by rbeyer** [USGS-Astrogeology/autocnet#563]
Follwing the README section on [How to run the test suite locally](https://github.com/USGS-Astrogeology/autocnet#how-to-run-the-test-suite-locally), I get the following error:
```
> docker run --name testdb -e POSTGRES_PASSOWRD='NotTheDefault' -e POSTGRES_USER='postgres' -p 5432:5432 -d mdillon/postgis
Unable to find image 'mdillon/postgis:latest' locally
latest: Pulling from mdillon/postgis
f7e2b70d04ae: Pull complete
027ad848ac9c: Pull complete
7c040ef66643: Pull complete
b891079ad2eb: Pull complete
cb64a97e42d9: Pull complete
1b88625f7d89: Pull complete
a6ac0b663e77: Pull complete
594497f0a694: Pull complete
ca7201b6a21f: Pull complete
48cdfad3f2fd: Pull complete
912fb62e7390: Pull complete
1e6365c64609: Pull complete
eda829b73ec7: Pull complete
1dafb86732d6: Pull complete
ad1854653222: Pull complete
410147bb9559: Pull complete
ee8d11af0d8f: Pull complete
Digest: sha256:ac5dd18c43b0ee89320764684aa5c2da5c3c2ce54cf01a6caab21f905302d1b5
Status: Downloaded newer image for mdillon/postgis:latest
3fac5e4ccf7710a4d394c043ab55b64d750841396dd720376d8641c6fe516cc5

> docker exec testdb psql -c 'create database template_postgis;' -U postgres
ERROR:  database "template_postgis" already exists
```

However, when I just ignored it, I was able to successfully run `pytest autocnet`, so 🎉 

Is the database create not needed anymore (because the docker image got updated?), is it only needed sometimes, or not others?  

The step either needs to be dropped from the instructions, or Dear Reader needs to be given a warning that they might get an error, and why.

**Comment by jlaura** [comment]
@rbeyer  I have seen this too and assumed it was a local setup issue! So woot, looks like that step can be removed. I'll get a PR open on the README.

Going to add you to this repo as well so that I can tag you in README reviews and allow you to merge them.
