### ISSUE TITLE
Upgrade to post-1.0 version of pvl

### ISSUE THREAD

**Issue by rbeyer** [USGS-Astrogeology/autocnet#564]
Wanted to give this a try, and did `mamba install pvl==1.2.0`.

In order to do so, it would need to upgrade 
```
  Package   Version  Build           Channel                  Size
────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────

  blas          1.1  openblas        conda-forge/osx-64     Cached
  openblas    0.3.4  hdc02c5d_1000   conda-forge/osx-64      18 MB

  Upgrade:
────────────────────────────────────────────────────────────────────

  - ale         0.8.4  py37hb449ec0_1  installed
  + ale         0.8.6  py37h737db71_0  conda-forge/osx-64     199 KB
  - plio        1.2.3  py37hc8dfbb8_1  installed
  + plio        1.2.5  py37hf985489_0  conda-forge/osx-64       4 MB
  - pvl         0.3.0  py_1            installed
  + pvl         1.2.0  pyhd8ed1ab_0    conda-forge/noarch     Cached
  - scipy       1.2.1  py37hbd7caa9_1  installed
  + scipy       1.6.2  py37h4420a3a_1  pkgs/main/osx-64        18 MB

  Summary:

  Install: 2 packages
  Upgrade: 4 packages

  Total download: 40 MB
```

The dependency constraints of *plio* and *scipy* listed in `environment.yml` prevent this upgrade.

Latest *plio* updated its dependency on *pvl*.  Are there other usage items that prevent upgrade to latest *plio*?

Not sure why *scipy* would be getting upgraded here?  Maybe something related to the *plio* upgrade?  Why does autocnet constrain the scipy version?

Comments can be placed in YAML files, and when dependencies are restricted, they should be documented.

Anyway, I went ahead and did the upgrade in a cloned environment.  The test suite didn't yield any problems (but its got a pretty low coverage).

**Comment by jessemapel** [comment]
#562 fixes this for PVL. We just got the Pvl 1.0+ compatible version of PLIO released. I'm not sure what's going on with the scipy dependency. ALE expects >=1.4.0 for the changes to the rotations interface.

It could be the knoten dependency that's causing issues. I'm not sure where that is being used. Considering that package has environment issues related to needing the new PLIO, it may need to be re-released too.

**Comment by rbeyer** [comment]
It doesn't really.  #562 upgrades the environment.yml file(s), but the code in *autocnet* that uses the *pvl* module (graph/node.py and bin/acn_load_images) relies on the pre-1.0 version of pvl that returned bytestrings, and will fail.  The 1+ version returns Python strings, like a sane Python 3 library should.

Humorously, none of these errors are caught by the current test suite, but anyone that tries to use these modules will get an error, because the returned string won't have a decode() function.

Also matcher/cross_instrument_matcher.py imports pvl, but doesn't use it.

I've got branch which fixes this ready to go, but seems like I should wait for #562 to land.

**Comment by jessemapel** [comment]
We also need to keep the PVL pinning in #562 if we are dependent on Pvl +- 1.0

**Comment by rbeyer** [comment]
> We also need to keep the PVL pinning in #562 if we are dependent on Pvl +- 1.0

Oh yes.

**Comment by jlaura** [comment]
This PR has removed 2 unused acn_* scripts and added some more text to the README. It is ready for a review.

https://github.com/USGS-Astrogeology/autocnet/pull/565/files

**Comment by rbeyer** [comment]
Oh, I want to be clear, I still have no idea how to use autocnet, I just grepped the codebase to find where and how it was using the Python *pvl* library.

However, even if you axe `bin/acn_load_images`, the `graph/node.py` module still does an [`import pvl`](https://github.com/USGS-Astrogeology/autocnet/blob/d3a2c47924c8219ae2bff21b25025cef8f445b63/autocnet/graph/node.py#L635).  If you want to remove pvl from your dependency list, you would need to address that, and the uneccesary import in `matcher/cross_instrument_matcher.py`.

**Comment by jessemapel** [comment]
@jlaura No we're using from_filelist to load our images.

I also agree with Ross that since we directly use PVL we need to have it as an explicit dependency, but if we're not using anything version specific we should not pin the version.
