### ISSUE TITLE
AutoCNet requires an ISISROOT for import

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#584]
When autocnet is imported it also ALWAYS imports the ISIS wrapper kalasiris (used to be pysis). ISIS is leveraged in AutoCNet for spatial interactions with images, namely image_to_ground and ground_to_image calls. Therefore, if you do not have an ISISROOT environment variable set at the time of autocnet import, it fails. However, AutoCNet has capabilities other than spatial image calls AND has an option for CSM cameras to handle those interactions. Therefore, AutoCNet should not be dependent on having an ISISROOT. Ideally, we would sequester the camera import and have hard failures only if a spatial call was made without proper ISIS/CSM camera setups.

I was running into this problem while trying to generate the docs and created a less than ideal work around, when this is resolved, the following files should be updated:
- docs/conf.py
- docs/Makefile
The specific changes to be removed are highlighted in PR #583 .

**Comment by rbeyer** [comment]
If ISIS (and thus *kalasiris*) are optional for *AutoCNet* then the code should wrap its `import kalasiris` statements in try-except blocks to catch the exception that kalasiris throws.  You could either just emit a "doesn't have ISIS, can't do X, Y, Z" message there, or be smarter and figure out if the input files don't need ISIS (and so this thrown exception is okay to be quietly ignored), or if the input files really do need ISIS, and this is, in fact a real exception that needs to be passed on to the user.

Alternately, you could move those `import kalasiris` statements down into the functions that call ISIS.  So if someone is operating in *AutoCNet* and never calls functions that need ISIS, then `import kalasiris` never gets evaluated.
