### ISSUE TITLE
KagTC images failing campt

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/autocnet#606]
This ticket applies to PR #605 

If I use the new smart_register_point

```
shared_kwargs = {'geom_func':'simple',
                 'match_func':'classic',
                 'cost_func':lambda x,y:y,
                 'chooser':'smart?'}
parameters = [
    {'match_kwargs': {'image_size':(121,121), 'template_size':(61,61)}},
    {'match_kwargs': {'image_size':(151,151), 'template_size':(67,67)}},
    {'match_kwargs': {'image_size':(181,181), 'template_size':(73,73)}},
    {'match_kwargs': {'image_size':(221,221), 'template_size':(81,81)}},
    {'match_kwargs': {'image_size':(251,251), 'template_size':(89,89)}},
    {'match_kwargs': {'image_size':(281,281), 'template_size':(98,98)}}
]
njobs = ncg.apply('matcher.subpixel.smart_register_point',
                  on='points', # function kwargs start
                  query_string = "SELECT * FROM points LIMIT 10",
                  walltime="01:00:00", # apply kwargs start
                  log_dir=subpix_log_dir,
                  arraychunk=100,
                  chunksize=20000,
                  jobname='SVDFAutocnetNetwork_SmartSubpixel',
                  # Args for the called func
                  parameters=parameters,
                  shared_kwargs=shared_kwargs,) # maximum chunksize = 20,000

print(njobs)

```

it give the following error for TC images
```
geom_match image: /scratch/ladoramkershner/moon/kaguya/2021_mosaics/reiner_gamma/evening/control/lvl1/TC1W2B0_01_01070N096E3050.lev1.cub
geom_func <function geom_match_simple at 0x2abf9d89e7a0>
[(303, 2304), (303, 2424), (423, 2424), (423, 2304), (363.59998830359, 2364.5999884741)]
Processing:  303 2304
Command '['campt', 'from=/scratch/ladoramkershner/moon/kaguya/2021_mosaics/reiner_gamma/evening/control/lvl1/TC1W2B0_01_05750N101E3046.lev1.cub', 'coordlist=/tmp/tmpqzu1upph', 'allowoutside=False', 'usecoordlist=True', 'coordtype=image']' died with <Signals.SIGABRT: 6>.
```

but if I try to run the campt call directly (taken from line 2061 in matcher/subpixel.py)
```
from autocnet import spatial
base_cube_filename = '/scratch/ladoramkershner/moon/kaguya/2021_mosaics/reiner_gamma/evening/control/lvl1/TC1W2B0_01_05750N101E3046.lev1.cub'
x = 303
y = 2304
lon, lat = spatial.isis.image_to_ground(base_cube_filename, x, y)
print(lon, lat)
```
I get `304.98497304206 10.105985921935` returned. This new smart subpixel matcher is being used successfully on CTX images as part of the CTX mosaic project. So I think it may have something to do with the trouble we have been having with the KaguyaTC cameras in ISIS. On that note I am using ISIS version isis4.0.0 in my autocnet environment.

I have created a notebook that runs both of these functions (plus the set up of the autocnet environment and the network I am working on), please message me for the path information when you pick up this ticket.

**Comment by jlaura** [comment]
@AustinSanders This is an important support one for me.

@ladoramkershner If this percolates as high priority for support, I am happy to take a first stab at it.

**Comment by jlaura** [comment]
I am testing this against ISIS6.0.0 through autocnet and kalisiris. Direct calls to spatial.isis.point_info, spatial.isis.image_to_ground and spatial.isis.ground_to_image all work as expected. I tested on both a random TC image and the image posted above in the bug report (copied the exact file locally). 

I will update after I test using this via geom_match.

**Comment by jlaura** [comment]
I can see that these images do overlap as expected and that the a priori pointing is close enough that the method should be working (though the a priori pointing is not great!)
<img width="1076" alt="Screen Shot 2021-11-03 at 1 49 50 PM" src="https://user-images.githubusercontent.com/2105468/140190679-19c1dfb6-7ff2-4a00-8dcd-bf388a9a69b1.png">

**Comment by jlaura** [comment]
So, it looks like the reference measure / image is getting swapped someplace. From the logs provided by the OP, it looks like the left image (above) is the reference. In reality, the right image is the reference and the provided coordinates do provide a valid affine transformation.
