### ISSUE TITLE
Undefined Names Everywhere

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/autocnet#63]
Undefined name combined in io_ccs.py
https://github.com/USGS-Astrogeology/autocnet/blob/master/autocnet/fileio/io_ccs.py#L129

Undefined name xrange in io_multibandimager.py
https://github.com/USGS-Astrogeology/autocnet/blob/master/autocnet/fileio/io_multibandimager.py#L9

Undefined name value in io_moon_minerology_mapper.py
https://github.com/USGS-Astrogeology/autocnet/blob/master/autocnet/fileio/io_moon_minerology_mapper.py#L18

Undefined name f in io_yaml.py
https://github.com/USGS-Astrogeology/autocnet/blob/master/autocnet/fileio/io_yaml.py#L21

Undefined name plotFeatures in graph_view.py
https://github.com/USGS-Astrogeology/autocnet/blob/master/autocnet/vis/graph_view.py#L242

Undefined name specturm (maybe misspelled?) in analytics.py
https://github.com/USGS-Astrogeology/autocnet/blob/master/autocnet/spectral/analytics.py#L89

Undefined name norm in spectral_data.py
https://github.com/USGS-Astrogeology/autocnet/blob/master/autocnet/spectral/spectral_data.py#L26

Undefined name os in test_three_image.py
https://github.com/USGS-Astrogeology/autocnet/blob/master/functional_tests/test_three_image.py#L76

Errors found using flake8. All other "errors" (pep8 compliance) are either assigned but never used due to the code that uses it being commented out or are line length errors.

**Comment by jlaura** [comment]
@RyanA1084 Can you take a look at these that are in the PR that you put in (at some point).  We are moving towards PEP8 compliance and these will throw errors.

Thanks!

**Comment by RyanA1084** [comment]
Ok, I'll take a look at these when I get the chance.

**Comment by jlaura** [comment]
This code was pulled into the PySAT repo so that this code could continue to be kept clean.

**Comment by ryanbanderson** [comment]
Ok, I'll work in the PySAT repo from now on. There should be a lot more activity on this soon: I have a student contractor that started yesterday to help me with this work.
